-- Support Carrier Init anim
function Init()
	Sleep(30) -- to let the MoveCtrl move it
	EmitSfx(piece("bodyemit0"), 1027)
	EmitSfx(piece("bodyemit1"), 1027)
	Turn(piece("tp_1_1"), y_axis, math.rad(-80))
	Turn(piece("tp_1_2"), y_axis, math.rad(-120))
	Turn(piece("tp_1_3"), y_axis, math.rad(-150))
	Turn(piece("tp_1_4"), y_axis, math.rad(80))
	Turn(piece("tp_1_5"), y_axis, math.rad(120))
	Turn(piece("tp_1_6"), y_axis, math.rad(150))
end

-- Support Carrier Killed anim
function script.Killed(recentDamage, maxHealth)
	local left, right, enginer, enginel = piece("left", "right", "enginer", "enginel")
	local enginelemit, engineremit, leftemit, rightemit = piece("enginelemit", "engineremit", "leftemit", "rightemit")
	local platform0 = piece("platform0")
	Move(left, x_axis, 90, 19)
	Move(right, x_axis, -90, 31)
	Move(enginer, x_axis, -90, 14)
	Move(enginer, z_axis, -90, 11)
	Move(enginel, x_axis, 90, 18)
	Move(enginel, z_axis, -90, 8)
	Sleep(700)
	Hide(body)
	GG.RecursiveHide(unitID, info.turretIDs[4], true)
	Sleep(900)
	EmitSfx(leftemit, 1026)
	Sleep(300)
	GG.RecursiveHide(unitID, left, true)
	Sleep(600)
	EmitSfx(rightemit, 1024)
	EmitSfx(platform0, 1024)
	EmitSfx(info.barrelIDs[1], 1024)
	Sleep(100)
	GG.RecursiveHide(unitID, right, true)
	Sleep(300)
	EmitSfx(engineremit, 1026)
	EmitSfx(engineremit, 1024)
	Sleep(300)
	GG.RecursiveHide(unitID, enginer, true)
	Sleep(800)
	EmitSfx(enginelemit, 1025)
	Sleep(700)
	GG.RecursiveHide(unitID, enginel, true)
	return 0
end